# Generated by Django 3.0.2 on 2020-02-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='base_url',
            field=models.URLField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
